export const BEGINNER_BOARD: BeginnerBoard = {
  tiles: {
    "0,-2,2": { resource: "ore", numberToken: 10 },
    "1,-2,1": { resource: "wool", numberToken: 2 },
    "2,-2,0": { resource: "lumber", numberToken: 9 },
    "-1,-1,2": { resource: "grain", numberToken: 12 },
    "0,-1,1": { resource: "brick", numberToken: 6 },
    "1,-1,0": { resource: "wool", numberToken: 4 },
    "2,-1,-1": { resource: "brick", numberToken: 10 },
    "-2,0,2": { resource: "grain", numberToken: 9 },
    "-1,0,1": { resource: "lumber", numberToken: 11 },
    "0,0,0": { resource: "desert", numberToken: null },
    "1,0,-1": { resource: "lumber", numberToken: 3 },
    "2,0,-2": { resource: "ore", numberToken: 8 },
    "-2,1,1": { resource: "lumber", numberToken: 8 },
    "-1,1,0": { resource: "ore", numberToken: 3 },
    "0,1,-1": { resource: "grain", numberToken: 4 },
    "1,1,-2": { resource: "wool", numberToken: 5 },
    "-2,2,0": { resource: "brick", numberToken: 5 },
    "-1,2,-1": { resource: "grain", numberToken: 6 },
    "0,2,-2": { resource: "wool", numberToken: 11 },
  },
  roads: {
    "0.5,-1.5,1": { player: "red" },
    "-1.5,0.5,1": { player: "red" },
    "1.5,-1.5,0": { player: "green" },
    "-0.5,1.5,-1": { player: "green" },
    "-1.5,1.5,0": { player: "blue" },
    "0.5,1,-1.5": { player: "blue" },
    "-1,-0.5,1.5": { player: "purple" },
    "1.5,0,-1.5": { player: "purple" },
  },
  settlements: {
    "0.5,-1.5,1.5": { player: "red" },
    "-1.5,0.5,1.5": { player: "red" },
    "1.5,-1.5,-0.5": { player: "green" },
    "-0.5,1.5,-0.5": { player: "green" },
    "-1.5,1.5,0.5": { player: "blue" },
    "0.5,1.5,-1.5": { player: "blue" },
    "-0.5,-0.5,1.5": { player: "purple" },
    "1.5,0.5,-1.5": { player: "purple" },
  },
};
