import { generateBoard } from "~~/lib/board/generateBoard";

export const beginnerInitialState: ServerGameState = {
  board: generateBoard(),
  turn: 0,
  turnPhase: {
    main: "roll",
    sub: null,
  },
  actionLog: [],
  resources: {
    wool: 19,
    brick: 19,
    lumber: 19,
    grain: 19,
    ore: 19,
  },
  socketAssignments: [],
  players: [
    {
      visibleResources: true,
      name: "Red",
      color: "red",
      settlements: 5,
      cities: 4,
      roads: 15,
      victoryPoints: 2,
      wool: 0,
      brick: 0,
      lumber: 2,
      grain: 1,
      ore: 0,
      resourceCount: 3,
    },
    {
      visibleResources: true,
      name: "Blue",
      color: "blue",
      settlements: 5,
      cities: 4,
      roads: 15,
      victoryPoints: 2,
      wool: 0,
      brick: 1,
      lumber: 1,
      grain: 0,
      ore: 1,
      resourceCount: 3,
    },
    {
      visibleResources: true,
      name: "Green",
      color: "green",
      settlements: 5,
      cities: 4,
      roads: 15,
      victoryPoints: 2,
      wool: 0,
      brick: 0,
      lumber: 0,
      grain: 2,
      ore: 1,
      resourceCount: 3,
    },
    {
      visibleResources: true,
      name: "Purple",
      color: "purple",
      settlements: 5,
      cities: 4,
      roads: 15,
      victoryPoints: 2,
      wool: 0,
      brick: 1,
      lumber: 1,
      grain: 1,
      ore: 0,
      resourceCount: 3,
    },
  ],
};
